# Generated by Django 5.0.2 on 2025-03-05 07:34

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Flagged', 'Flagged')], default='Pending', max_length=10)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('confidence_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('number_of_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('supplier_address', models.TextField()),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Information',
                'verbose_name_plural': 'Invoice Information',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='api_invoice_invoice_63f567_idx'), models.Index(fields=['user'], name='api_invoice_user_id_b3d5e2_idx'), models.Index(fields=['status'], name='api_invoice_status_398c55_idx'), models.Index(fields=['created_at'], name='api_invoice_created_417a4d_idx')],
            },
        ),
    ]
